### PR TITLE
Upgraded to 0.9.4

### PR DESCRIPTION
**Pull request by frol**

### CODE REVIEW

**Comment by frol** [comment]
@jakirkham Hi! I am sorry to bother you again, but it seems that there is something wrong with CircleCI; it skipped the build for this PR with "NOT RUNNING" state: https://circleci.com/gh/conda-forge/flask-oauthlib-feedstock/13. Is this fine?

**Comment by jakirkham** [comment]
No bother at all.

Weird. I saw something similar like this with the `scipy` feedstock the other day. Hadn't really seen it since. Maybe there is some low frequency issue we are encountering with CircleCI.

In any event, canceling that build and restarting it appears to have created a new build with the `scheduled` status. That actually isn't surprising as we have a lot of builds going in order to rebuild everything for NumPy 1.13, which was released recently. Also we are now seeing the CircleCI status on the PR, which we weren't previously.

Guessing this has fixed the issue. Though if you see anything else strange, please let us know.

**Comment by frol** [comment]
All tests are passed! It is ready to merge.

**Comment by frol** [comment]
@pmlandwehr @jakirkham I am kindly pinging you for getting this merged.

**Pull request merged**
